export const cues = [
  {
    id: "house-loop",
    number: "H0",
    section: "Pre-show",
    label: "Blackout before start",
    projector: "black",
    audio: false,
    ipad: "black",
    progress: 0,
    progressRange: [0, 0],
    floorLoading: false,
    note: "Safe preset. Hold all outputs black until the first GO."
  },
  {
    id: "preshow-get-ready",
    number: "H1",
    section: "Pre-show / Gong 1",
    label: "Get Ready With Me · audience entry loop",
    projector: "hero",
    media: "/assets/video/hero.mp4",
    assets: ["hero-video"],
    fallbackProjector: "hero",
    loop: true,
    audio: true,
    fit: "portrait-right",
    stoneOcclusion: true,
    ipad: "black",
    progress: 0,
    progressRange: [0, 0],
    floorLoading: false,
    note: "Audience-entry background video and sound. Let it loop until the Gong 3 GO."
  },
  {
    id: "fragment-1-hero",
    number: "F1.1",
    section: "Fragmen I / Gong 3",
    label: "Fade Get Ready to blackout",
    projector: "preshow-fade",
    media: "/assets/video/hero.mp4",
    assets: ["hero-video"],
    fallbackProjector: "hero",
    loop: true,
    audio: true,
    fit: "portrait-right",
    preservePlayback: true,
    fadeDuration: 4,
    stoneOcclusion: true,
    ipad: "idle",
    progress: 0,
    progressRange: [0, 0],
    floorLoading: false,
    note: "One GO fades picture and programme audio over 4 seconds, then holds black for the MC opening."
  },
  {
    id: "fragment-2-loading",
    number: "F2.1",
    section: "Fragmen II",
    label: "Loading UI 1% → 49%",
    projector: "loading",
    surface: "floor",
    stoneOcclusion: true,
    ipad: "idle",
    progress: 1,
    progressRange: [1, 49],
    floorLoading: true,
    note: "Remain alive for the entire fragment. Progress is operator-controlled."
  },
  {
    id: "fragment-2-milo",
    number: "F2.2",
    section: "Fragmen II",
    label: "Iklan Milo",
    projector: "video",
    media: "/assets/video/milo.mp4",
    assets: ["milo"],
    loop: false,
    audio: true,
    fit: "contain",
    stoneOcclusion: true,
    ipad: "idle",
    progress: 12,
    progressRange: [1, 49],
    floorLoading: true,
    note: "Source/permission: IG Iyas. Keep loading state available underneath."
  },
  {
    id: "fragment-2-camera",
    number: "F2.3",
    section: "Fragmen II",
    label: "Live camera: objects on table",
    projector: "camera",
    stoneOcclusion: true,
    ipad: "idle",
    progress: 22,
    progressRange: [1, 49],
    floorLoading: true,
    note: "Camera source must be tested and permission granted before house opens."
  },
  {
    id: "fragment-2-slideshow",
    number: "F2.4",
    section: "Fragmen II",
    label: "Slideshow / body updates",
    projector: "slideshow",
    data: "/assets/image/nugget-series/slideshow.json",
    assets: ["slideshow"],
    background: "#000000",
    foreground: "#f6edf0",
    ipad: "idle",
    progress: 34,
    progressRange: [1, 49],
    floorLoading: true,
    note: "Launch any spoken vocabulary directly from the dedicated iPhone nugget pad. TUHAN retains its repeated zoom treatment."
  },
  {
    id: "transition-1-aquarium",
    number: "T1.1",
    section: "Transisi I",
    label: "Aquariums + ocean fish tank back wall",
    projector: "video",
    media: "/assets/video/ocean-fishtank.mp4",
    assets: ["aquarium-back-wall"],
    loop: true,
    audio: false,
    ipad: "aquarium",
    progress: 49,
    progressRange: [49, 66],
    floorLoading: false,
    floorFishIndicator: true,
    note: "One scene: three iPads render the shared aquarium fish while the back wall loops Ocean Fish Tank silently. The floor shows three faint adjoining squares and a small bright, horizontally mirrored X-position marker for the actor. The marker wraps from square 3 to square 1 like the iPad aquarium world; the loading bar remains off."
  },
  {
    id: "fragment-3-budget",
    number: "F3.1",
    section: "Fragmen III",
    label: "Personal budgeting 50/30/20",
    projector: "spreadsheet",
    surface: "floor",
    ipad: "idle",
    progress: 66,
    progressRange: [66, 66],
    floorLoading: false,
    note: "Floor projection. Use mapping preset FLOOR."
  },
  {
    id: "fragment-3-loading",
    number: "F3.2",
    section: "Fragmen III",
    label: "Loading UI 66% → 76%",
    projector: "loading",
    surface: "floor",
    ipad: "idle",
    progress: 66,
    progressRange: [66, 76],
    floorLoading: true,
    note: "Start immediately after spreadsheet and remain alive through fragment."
  },
  {
    id: "fragment-3-face",
    number: "F3.3",
    section: "Fragmen III",
    label: "Kala face projection",
    projector: "kala-face",
    data: "/assets/image/kala-face/manifest.json",
    assets: ["kala-face"],
    directOverlay: true,
    surface: "screen",
    target: "kala-face",
    ipad: "idle",
    progress: 66,
    progressRange: [66, 76],
    floorLoading: true,
    note: "The keystoned back wall stays black while Kala renders on a direct foreground overlay. Move the pointer on the back-wall projector to drive the face across its entire window with no smoothing; H0 calibrates one uniform scale only. Face makeup changes automatically every three seconds; PULSE forces another change."
  },
  {
    id: "fragment-3-ibu-riri",
    number: "F3.4",
    section: "Fragmen III",
    label: "Ibu Riri",
    projector: "video",
    media: "/assets/video/fragment-3-ibu-riri-rain.mov",
    assets: ["fragment-3-ibu-riri-rain"],
    loop: true,
    audio: false,
    surface: "screen",
    ipad: "idle",
    progress: 66,
    progressRange: [66, 76],
    floorLoading: true,
    note: "Rain video loops on the back wall for Ibu Riri and stops immediately when the next cue is selected."
  },
  {
    id: "transition-2-organs",
    number: "T2.1",
    section: "Transisi II",
    label: "Objects video + live stone mask",
    projector: "stone-mask",
    media: "/assets/video/transition-2-objects.mov",
    auxiliaryMedia: "/assets/video/transition-2-stone.mov",
    assets: ["transition-2-objects", "transition-2-stone"],
    fallbackProjector: "stone-mask",
    loop: false,
    auxiliaryLoop: true,
    backgroundDim: 0.3,
    audio: true,
    stoneOcclusion: true,
    surface: "screen",
    target: "stone",
    ipad: "idle",
    progress: 76,
    progressRange: [76, 76],
    floorLoading: false,
    note: "Aku dan Barang-Barang plays once with sound across the back wall. The open operator stroke is projected as a white 80%-opacity line for physical tracing; the 28 px close target stays operator-only. Closing removes the guide and reveals the muted stone video cover-fitted to the completed mask bounds. The stone video loops until the back-wall video ends, then holds with it."
  },
  {
    id: "fragment-4-blackout",
    number: "F4.0",
    section: "Fragmen IV",
    label: "Blackout before Fragment IV",
    projector: "black",
    audio: false,
    ipad: "black",
    progress: 76,
    progressRange: [76, 76],
    floorLoading: false,
    note: "Full blackout between T2.1 and F4.1. Hold until the Fragment IV start cue."
  },
  {
    id: "fragment-4-roblox",
    number: "F4.1",
    section: "Fragmen IV",
    label: "Roblox video",
    projector: "video",
    media: "/assets/video/fragment-4-roblox.mov",
    assets: ["roblox"],
    loop: false,
    audio: true,
    ipad: "idle",
    progress: 76,
    progressRange: [76, 99.9],
    floorLoading: true,
    note: "Asset: Angel. Video transitions into So Asu sequence."
  },
  {
    id: "fragment-4-loading",
    number: "F4.2",
    section: "Fragmen IV",
    label: "Loading UI 76% → 99.9%",
    projector: "loading",
    surface: "floor",
    ipad: "idle",
    progress: 76,
    progressRange: [76, 99.9],
    floorLoading: true,
    note: "Remain alive across the whole fragment; RT/R2 is hard-capped at 99.9% and LT/L2 may reverse."
  },
  {
    id: "fragment-4-kodelife",
    number: "F4.3",
    section: "Fragmen IV",
    label: "KodeLife via OBS + soundtrack",
    projector: "camera",
    media: "/assets/audio/fragment-4-kodelife.m4a",
    assets: ["fragment-4-kodelife-audio"],
    loop: true,
    audio: true,
    surface: "screen",
    ipad: "idle",
    progress: 88,
    progressRange: [76, 99.9],
    floorLoading: true,
    note: "Fullscreen local camera feed with the looping Fragment IV soundtrack. Select the OBS Virtual Camera on the back-wall window, then switch OBS between the iPhone/table source and KodeLife capture. The soundtrack stops and resets on the next cue."
  },
  {
    id: "fragment-5-objects",
    number: "F5.1",
    section: "Fragmen V",
    label: "Reverse video",
    projector: "video",
    media: "/assets/video/fragment-5-reverse.mp4",
    assets: ["outro-back-wall"],
    loop: false,
    audio: true,
    fadeOutDuration: 5,
    stoneOcclusion: true,
    ipad: "idle",
    progress: 99.9,
    progressRange: [99.9, 99.9],
    floorLoading: false,
    note: "Prepared final reverse video on the back wall. Picture and any embedded audio fade smoothly to black over the final five seconds."
  },
  {
    id: "end-black",
    number: "END",
    section: "End",
    label: "Show-end blackout",
    projector: "black",
    stoneOcclusion: true,
    ipad: "black",
    progress: 99.9,
    progressRange: [99.9, 99.9],
    floorLoading: false,
    note: "The show has ended. Hold black before the curtain-call GO."
  },
  {
    id: "curtain-call-under-pressure",
    number: "CALL",
    section: "Curtain call",
    label: "Under Pressure · actor calls",
    projector: "video",
    media: "/assets/video/under-pressure.mp4",
    assets: ["under-pressure"],
    loop: false,
    audio: true,
    stoneOcclusion: true,
    ipad: "black",
    progress: 99.9,
    progressRange: [99.9, 99.9],
    floorLoading: false,
    note: "Offline fullscreen Under Pressure playback after the show-end blackout. Complete every actor call before the video finishes."
  },
  {
    id: "exit-black",
    number: "EXIT",
    section: "Post-show",
    label: "Final blackout",
    projector: "black",
    stoneOcclusion: true,
    ipad: "black",
    progress: 99.9,
    progressRange: [99.9, 99.9],
    floorLoading: false,
    note: "Hold black after the curtain call and during audience exit."
  }
];

export const cueById = new Map(cues.map((cue, index) => [cue.id, { ...cue, index }]));

export function cueProgressRange(cue) {
  const candidate = Array.isArray(cue?.progressRange) ? cue.progressRange : [0, 100];
  const minimum = Math.min(100, Math.max(0, Number(candidate[0]) || 0));
  const maximum = Math.min(100, Math.max(minimum, Number(candidate[1]) || 0));
  return [minimum, maximum];
}
